# Generated by Django 5.0.6 on 2024-06-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0004_remove_borrowing_unique_borrowing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("paid", "PAID")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("payment", "PAYMENT"), ("fine", "FINE")],
                        default="payment",
                        max_length=10,
                    ),
                ),
                ("session_url", models.URLField(max_length=10000)),
                ("session_id", models.CharField(max_length=10000)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
