# Generated by Django 5.0.6 on 2024-06-11 21:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_book_unique_book"),
        ("borrowing", "0002_alter_borrowing_actual_return_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(default=datetime.date(2024, 6, 19)),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.UniqueConstraint(
                fields=("book", "user"), name="unique_borrowing"
            ),
        ),
    ]
