# Generated by Django 5.0.6 on 2024-06-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0003_alter_borrowing_expected_return_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="unique_borrowing",
        ),
    ]
